version: "3"

tasks:
  download-mmd:
    desc: Download the mmdetection repository
    cmds:
      - git clone https://github.com/open-mmlab/mmpretrain
      - git clone https://github.com/open-mmlab/mmdetection.git
      - git clone https://github.com/open-mmlab/mmsegmentation
    dir: .
  
  install-mm:
    desc: Install the mmdetection library
    cmds:
      - mim uninstall -y mmengine mmcv mmpretrain mmdet mmsegmentation
      - mim install -U mmengine mmcv==2.1 mmpretrain mmdet mmsegmentation
    dir: .

  run-tests:
    desc: Run tests
    cmds:
      - pytest tests/
    dir: .
  
  
